### PR TITLE
Add .gitignore file

### PR DESCRIPTION
**Pull request by paulmasson**
This should take care of the desktop.ini files in the future. Deleting existing files at the same time.

### CODE REVIEW

**Comment by paulmasson** [comment]
@landgreen based on your commit history, it looks like you're using the GitHub web interface only. You might also be interested in the [desktop](https://desktop.github.com/) version of GitHub. It makes certain tasks simpler, like deleting multiple files in a single commit, because you work on a local copy of the repository.

And FYI the .gitignore control doesn't filter files uploaded through the website, so you've add at least one more desktop.ini back in.

**Comment by landgreen** [comment]
I've been putting off learning the git interface, but now that I've got some attention on the repository I'll be motivated to go learn the command line.  My plan is to figure out how to integrate github into VSCode, which is probably going to change in the future since microsoft is buying github.

If you have any more advice I find it super helpful (and I'll pass it on to my students).

**Comment by paulmasson** [comment]
The beauty of desktop GitHub is that while you can use the command line, for most things you don't have to do so. It's a graphical interface to the command line and much easier to use. Well worth a bit of time getting familiar with it.

**Comment by landgreen** [comment]
I've got it installed and I'm playing with my test repo.  (although I should be grading lab reports)

**Pull request merged**
