### PR TITLE
Fix applyGravity() to avoid precessing circular orbits

### PR DESCRIPTION
**Pull request by paulmasson**
This small edit will avoid the precessing circular orbits mentioned on Reddit:

https://www.reddit.com/r/Physics/comments/8my98x/online_physics_course_notes_with_javascript/dzrfnki/

I'm assuming you added the offset to prevent infinities in gravitational collisions, but the value is much too large. If you want to keep it in, you could try something much smaller, but it would probably be better to handle collisions in other ways.

FYI your technique of integration goes by the name of the [Euler method](https://en.wikipedia.org/wiki/Euler_method). It's fine for small time steps and total integration times that are not too large.

### CODE REVIEW

**Comment by paulmasson** [comment]
@landgreen did you intend to push to my fork or was that unintentional?

**Comment by landgreen** [comment]
I intended to not use the code, but only because I had already noticed the problem. I'm still learning github, so I was playing around with the UI on a commit. I think I edited your code to look like mine and then I merged it.

Thanks for the edit btw.  It looks like you are a bit of an expert on physics simulations.  What do you think of my new method?  I think it might be Leapfrog, but I have trouble telling the difference between that and Euler, anyways I'm not use trig functions anymore so I hope it will speed up the integration.

```
  //http://www.artcompsci.org/msa/web/vol_1/v1_web.pdf
  static integration(who) {
    const minDistance2 = 100;
    for (let i = 0, len = who.length; i < len; ++i) {
      //change position from velocity
      who[i].position.x += who[i].velocity.x;
      who[i].position.y += who[i].velocity.y;
      //accelerate from gravity
      for (let j = 0, len = who.length; j < len; ++j) {
        if (i < j) {
          const dx = who[i].position.x - who[j].position.x;
          const dy = who[i].position.y - who[j].position.y;
          const d2 = Math.max(dx * dx + dy * dy, minDistance2);
          const mag = 0.05 / d2 / Math.sqrt(d2);
          who[i].velocity.x -= mag * who[j].mass * dx;
          who[i].velocity.y -= mag * who[j].mass * dy;
          who[j].velocity.x += mag * who[i].mass * dx;
          who[j].velocity.y += mag * who[i].mass * dy;
        }
      }
    }
  }
```

**Comment by landgreen** [comment]
Wow, I'm looking at your Analytic Physics page.  It is amazing.  I love the three.js sound stuff.  did you see my strange sound project with 2-d balls. https://landgreen.github.io/physics/notes/waves/waves/index.html#sound-waves

**Comment by paulmasson** [comment]
@landgreen you're right, what you're doing is essentially leapfrog, my bad. For the Euler method you would calculate deltas for position and velocity at the same time before updating variables. With leapfrog you update positions from the current velocity, then update velocities from the updated positions. I hadn't heard of that method before this conversation, so thanks for teaching me something. For long running simulations, you're better off using leapfrog as you are. And the updated code looks a lot cleaner.

I like your 2D balls! If you want to see a version of the 3D sound waves side-by-side with the Three.js code, then here's another project of mine:

http://exploratoria.github.io/exhibits/waves/plane-wave/index.html
http://exploratoria.github.io/exhibits/waves/cylindrical-wave/index.html
http://exploratoria.github.io/exhibits/waves/spherical-wave/index.html

There are additional exhibits with elastic collisions, light mixing and some mathematical objects. The project is intended to teach 3D coding.

**Comment by paulmasson** [comment]
Ross, I've always been interested in JavaScript simulations of <i>n</i>-body gravitational systems, but couldn't get them to be accurate with Euler integration. Thanks to reading your code, I switched to leapfrog integration and the resulting evolution is notably more stable and accurate. Here it is if you have an interest:

http://exploratoria.github.io/exhibits/astronomy/gravitating-system/

Thanks again for teaching me about leapfrog!

**Comment by landgreen** [comment]
Thanks, I learned about Leapfrog from /r/physics on reddit. 

I find the whole quest for a better n-body kinda exciting after reading the [3-body problem](https://en.wikipedia.org/wiki/The_Three-Body_Problem_(novel)) trilogy last year.

Oh, I'm looking to add more graphs 2-d, and 3-d to my physics site.  Do you recommend your mathcell library? It looks like exactly what I want, but I figured I'd ask just in case.

P.S. I'm enjoying the github desktop version.

**Comment by paulmasson** [comment]
Like any developer, I'm always interested in having people use my library. I've tried reaching out a bit with no substantive responses, and a project can't really grow without input from others. You're exactly the sort of forward-looking educator whose feedback would be most appreciated.

That being said, it depends on what you want to visualize and how. You already know about the two main options available now: D3 and JSXGraph. I personally found the learning curve for D3 so steep that is was simpler to write my own SVG plotting code, but it produces a certain look that people like. I don't like the interface for JSXGraph, since I wanted to replicate the feel of Mathematica's Manipulate command, but it does handle touch events like D3. Neither library does 3D, however.

Your website already has lots of animations, and that's one area where my project needs work. Since it takes little processing effort to produce reasonable SVGs, I can fudge 2D animations by simply replacing the output in an animation frame loop, but that's not the best way to do it. That approach won't work at all for 3D as I'm presenting it now. I've been thinking about ways to improve that but again input from users would be most helpful.

I'd certainly encourage you to try out MathCell and let me know if you find it easy to use or not. Since I wrote it I think it's simpler to get results for my use cases than D3 or JSXGraph would be, but I'm always eager to know what others think. As a JavaScript coder, you'll notice that my functions are in the global namespace: that's to make them work like Mathematica and SageMath commands, but could potentially lead to conflicts.

If you find there are visualizations you'd like to do with MathCell that can't be done yet, then please open an issue and describe the situation. I'm always adding new features that I need to use and can do the same for others, but again I need input. Perhaps that would be an interesting way to spend part of your summer!

**Comment by paulmasson** [comment]
And if you want to see some freaky three-body orbits, here something that I finally finished earlier this week:

[Simó's Three-Body Choreographies in Action](http://analyticphysics.com/Three-Body%20Problem/Sim%C3%B3's%20Three-Body%20Choreographies%20in%20Action.htm)

**Comment by paulmasson** [comment]
@landgreen don't know if you're into VR or not, but if so then here's a WebVR version of the 10-body  gravitating system mentioned above:

https://paulmasson.github.io/webvr-worlds/gravitating-system.html

It has basic navigation for thumbpads as described here: https://paulmasson.github.io/webvr-worlds/

Runs pretty well on my Oculus Go!

**Comment by landgreen** [comment]
I tried to view it with my google daydream (I got it free with my phone).
It said webVR wasn't supported.
They still look pretty good on my computer. The Jacobi might be my favorite.

I'll probably get more into three.js because I've got a couple students in
the computer science class I teach that are getting into it.

**Comment by paulmasson** [comment]
If you have at least Chrome 66 on your phone, you should be able to turn on WebVR by navigating to `chrome://flags/#enable-webvr ` and changing the setting.

If that doesn't work, here's a non-VR version of the Jacobi elliptic sine:

https://paulmasson.github.io/math/docs/functions/sn.html

Scroll down to the middle of the page and change the parameter settings to something nonzero, otherwise it's just a regular sine function. Here's a complete list of functions with links to visualizations, if you're interested:

https://paulmasson.github.io/math/docs/functions.html

**Pull request closed without merging**
